declare namespace c1 {
    export { t1 as colorToHex };
    export { e1 as colorToHsl };
    export { n1 as colorToHwb };
    export { r1 as colorToLab };
    export { s1 as colorToLch };
    export { a1 as colorToOklab };
    export { o1 as colorToOklch };
    export { i1 as colorToRgb };
    export { Ki as colorToXyz };
    export { l1 as colorToXyzD50 };
    export { J0 as numberToHex };
}
declare function Lr(t: any, e?: {}): any;
declare function Nu(t: any, e?: {}): string | String;
declare function K0(t: any): any;
declare function gn(t: any, e?: {}): boolean;
declare function $1(t: any, e?: {}): boolean;
declare function W0(t: any, e?: {}): any;
declare function ji(t: any, e?: string): any;
declare function t1(t: any, e?: {}): any;
declare function e1(t: any, e?: {}): any;
declare function n1(t: any, e?: {}): any;
declare function r1(t: any, e?: {}): any;
declare function s1(t: any, e?: {}): any;
declare function a1(t: any, e?: {}): any;
declare function o1(t: any, e?: {}): any;
declare function i1(t: any, e?: {}): any;
declare function Ki(t: any, e?: {}): any;
declare function l1(t: any, e?: {}): any;
declare function J0(t: any): any;
export { c1 as convert, Lr as cssCalc, Nu as cssVar, K0 as extractDashedIdent, gn as isColor, $1 as isGradient, W0 as resolve, ji as splitValue };
