export function sendMsg(msg: any): Promise<void>;
export function initExt(init?: boolean): Promise<Promise<any> | null>;
export function initCustomTheme(init?: boolean): Promise<Promise<any> | null>;
export function requestCustomTheme(bool?: boolean): Promise<Promise<any> | null>;
export function storeCustomTheme(): Promise<object>;
export function createPref(elm?: object): Promise<object>;
export function storePref(evt: object): Promise<any[]>;
export function toggleSubItems(evt: object): void;
export function toggleCustomThemeSettings(): void;
export function addCustomThemeListener(): Promise<void>;
export function setCustomThemeValue(obj?: object): Promise<void>;
export function addBookmarkLocations(): Promise<void>;
export function handleInitCustomThemeClick(evt: object): Promise<any>;
export function addInitCustomThemeListener(): Promise<void>;
export function handleInitExtClick(evt: object): Promise<any>;
export function addInitExtensionListener(): Promise<void>;
export function saveUserCss(): Promise<any> | null;
export function addUserCssListener(): Promise<void>;
export function handleInputChange(evt: object): Promise<any>;
export function addInputChangeListener(): Promise<void>;
export function setHtmlInputValue(data?: object): Promise<any[]>;
export function setValuesFromStorage(): Promise<any[]>;
export function handleMsg(msg: object): Promise<any[]>;
export { folderMap } from "./bookmark.js";
