export const favicon: Map<string, string>;
export const contextualIdentitiesIconName: Set<string>;
export const contextualIdentitiesIconColor: Set<string>;
export function tabIconFallback(evt: object): boolean;
export function addTabIconErrorListener(elm: object): Promise<void>;
export function setTabIcon(elm: object, info: object): Promise<void>;
export function setTabContent(tab: object, tabsTab: object): Promise<void>;
export function handleClickedTabAudio(elm: object): Promise<Promise<any> | null>;
export function tabAudioOnClick(evt: object): Promise<any> | null;
export function addTabAudioClickListener(elm: object): Promise<void>;
export function setTabAudio(elm: object, info: object, num?: number): Promise<void>;
export function setTabAudioIcon(elm: object, info: object): Promise<void>;
export function setCloseTab(elm: object, highlighted: boolean, num?: number): Promise<void>;
export function tabCloseOnClick(evt: object): Promise<any> | null;
export function preventDefaultEvent(evt: object): void;
export function addTabCloseClickListener(elm: object): Promise<void>;
export function setContextualIdentitiesIcon(elm: object, info: object): Promise<void>;
export function addHighlight(elm: object, num: number): Promise<any[]>;
export function addHighlightToTabs(tabIds: any[]): Promise<any[]>;
export function removeHighlight(elm: object): Promise<any[]>;
export function removeHighlightFromTabs(tabIds: any[]): Promise<any[]>;
