export namespace themeMap {
    namespace customTheme {
        export { CSS_VAR_BG as customBackgroundColor };
        export { CSS_VAR_BG_ACTIVE as customActiveBackgroundColor };
        export { CSS_VAR_BG_DISCARDED as customDiscardedBackgroundColor };
        export { CSS_VAR_BG_FIELD as customFieldBackgroundColor };
        export { CSS_VAR_BG_FIELD_ACTIVE as customFieldBackgroundActiveColor };
        export { CSS_VAR_BG_HOVER as customHoverBackgroundColor };
        export { CSS_VAR_BG_HOVER_SHADOW as customHoverBackgroundShadow };
        export { CSS_VAR_BG_SELECT as customSelectionBackgroundColor };
        export { CSS_VAR_BG_SELECT_HOVER as customHoverSelectionBackgroundColor };
        export { CSS_VAR_BORDER_ACTIVE as customActiveBorderColor };
        export { CSS_VAR_BORDER_FIELD as customFieldBorderColor };
        export { CSS_VAR_BORDER_FIELD_ACTIVE as customActiveFieldBorderColor };
        export { CSS_VAR_COLOR as customColor };
        export { CSS_VAR_COLOR_ACTIVE as customActiveColor };
        export { CSS_VAR_COLOR_DISCARDED as customDiscardedColor };
        export { CSS_VAR_COLOR_FIELD as customFieldColor };
        export { CSS_VAR_COLOR_FIELD_ACTIVE as customActiveFieldColor };
        export { CSS_VAR_COLOR_HOVER as customHoverColor };
        export { CSS_VAR_COLOR_SELECT as customSelectionColor };
        export { CSS_VAR_COLOR_SELECT_HOVER as customHoverSelectionColor };
        export { CSS_VAR_HEADING_TEXT_GROUP_1 as customTabGroup1HeadingText };
        export { CSS_VAR_HEADING_TEXT_GROUP_2 as customTabGroup2HeadingText };
        export { CSS_VAR_HEADING_TEXT_GROUP_3 as customTabGroup3HeadingText };
        export { CSS_VAR_HEADING_TEXT_GROUP_4 as customTabGroup4HeadingText };
        export { CSS_VAR_HEADING_TEXT_PINNED as customPinnedTabGroupHeadingText };
        export { CSS_VAR_OUTLINE_FOCUS as customFocusOutlineColor };
    }
    namespace alpenTheme {
        const customBackgroundColor: string;
        const customActiveBackgroundColor: string;
        const customDiscardedBackgroundColor: string;
        const customFieldBackgroundColor: string;
        const customFieldBackgroundActiveColor: string;
        const customFrameBackgroundColor: string;
        const customHoverBackgroundColor: string;
        const customHoverBackgroundShadow: string;
        const customSelectionBackgroundColor: string;
        const customHoverSelectionBackgroundColor: string;
        const customActiveBorderColor: string;
        const customFieldBorderColor: string;
        const customActiveFieldBorderColor: string;
        const customColor: string;
        const customActiveColor: string;
        const customDiscardedColor: string;
        const customFieldColor: string;
        const customActiveFieldColor: string;
        const customFrameColor: string;
        const customHoverColor: string;
        const customSelectionColor: string;
        const customHoverSelectionColor: string;
        const customTabGroup1HeadingText: string;
        const customTabGroup2HeadingText: string;
        const customTabGroup3HeadingText: string;
        const customTabGroup4HeadingText: string;
        const customPinnedTabGroupHeadingText: string;
        const customFocusOutlineColor: string;
    }
    namespace alpenDarkTheme {
        const customBackgroundColor_1: string;
        export { customBackgroundColor_1 as customBackgroundColor };
        const customActiveBackgroundColor_1: string;
        export { customActiveBackgroundColor_1 as customActiveBackgroundColor };
        const customDiscardedBackgroundColor_1: string;
        export { customDiscardedBackgroundColor_1 as customDiscardedBackgroundColor };
        const customFieldBackgroundColor_1: string;
        export { customFieldBackgroundColor_1 as customFieldBackgroundColor };
        const customFieldBackgroundActiveColor_1: string;
        export { customFieldBackgroundActiveColor_1 as customFieldBackgroundActiveColor };
        const customFrameBackgroundColor_1: string;
        export { customFrameBackgroundColor_1 as customFrameBackgroundColor };
        const customHoverBackgroundColor_1: string;
        export { customHoverBackgroundColor_1 as customHoverBackgroundColor };
        const customHoverBackgroundShadow_1: string;
        export { customHoverBackgroundShadow_1 as customHoverBackgroundShadow };
        const customSelectionBackgroundColor_1: string;
        export { customSelectionBackgroundColor_1 as customSelectionBackgroundColor };
        const customHoverSelectionBackgroundColor_1: string;
        export { customHoverSelectionBackgroundColor_1 as customHoverSelectionBackgroundColor };
        const customActiveBorderColor_1: string;
        export { customActiveBorderColor_1 as customActiveBorderColor };
        const customFieldBorderColor_1: string;
        export { customFieldBorderColor_1 as customFieldBorderColor };
        const customActiveFieldBorderColor_1: string;
        export { customActiveFieldBorderColor_1 as customActiveFieldBorderColor };
        const customColor_1: string;
        export { customColor_1 as customColor };
        const customActiveColor_1: string;
        export { customActiveColor_1 as customActiveColor };
        const customDiscardedColor_1: string;
        export { customDiscardedColor_1 as customDiscardedColor };
        const customFieldColor_1: string;
        export { customFieldColor_1 as customFieldColor };
        const customActiveFieldColor_1: string;
        export { customActiveFieldColor_1 as customActiveFieldColor };
        const customFrameColor_1: string;
        export { customFrameColor_1 as customFrameColor };
        const customHoverColor_1: string;
        export { customHoverColor_1 as customHoverColor };
        const customSelectionColor_1: string;
        export { customSelectionColor_1 as customSelectionColor };
        const customHoverSelectionColor_1: string;
        export { customHoverSelectionColor_1 as customHoverSelectionColor };
        const customTabGroup1HeadingText_1: string;
        export { customTabGroup1HeadingText_1 as customTabGroup1HeadingText };
        const customTabGroup2HeadingText_1: string;
        export { customTabGroup2HeadingText_1 as customTabGroup2HeadingText };
        const customTabGroup3HeadingText_1: string;
        export { customTabGroup3HeadingText_1 as customTabGroup3HeadingText };
        const customTabGroup4HeadingText_1: string;
        export { customTabGroup4HeadingText_1 as customTabGroup4HeadingText };
        const customPinnedTabGroupHeadingText_1: string;
        export { customPinnedTabGroupHeadingText_1 as customPinnedTabGroupHeadingText };
        const customFocusOutlineColor_1: string;
        export { customFocusOutlineColor_1 as customFocusOutlineColor };
    }
    namespace darkTheme {
        const customBackgroundColor_2: string;
        export { customBackgroundColor_2 as customBackgroundColor };
        const customActiveBackgroundColor_2: string;
        export { customActiveBackgroundColor_2 as customActiveBackgroundColor };
        const customDiscardedBackgroundColor_2: string;
        export { customDiscardedBackgroundColor_2 as customDiscardedBackgroundColor };
        const customFieldBackgroundColor_2: string;
        export { customFieldBackgroundColor_2 as customFieldBackgroundColor };
        const customFieldBackgroundActiveColor_2: string;
        export { customFieldBackgroundActiveColor_2 as customFieldBackgroundActiveColor };
        const customFrameBackgroundColor_2: string;
        export { customFrameBackgroundColor_2 as customFrameBackgroundColor };
        const customHoverBackgroundColor_2: string;
        export { customHoverBackgroundColor_2 as customHoverBackgroundColor };
        const customHoverBackgroundShadow_2: string;
        export { customHoverBackgroundShadow_2 as customHoverBackgroundShadow };
        const customSelectionBackgroundColor_2: string;
        export { customSelectionBackgroundColor_2 as customSelectionBackgroundColor };
        const customHoverSelectionBackgroundColor_2: string;
        export { customHoverSelectionBackgroundColor_2 as customHoverSelectionBackgroundColor };
        const customActiveBorderColor_2: string;
        export { customActiveBorderColor_2 as customActiveBorderColor };
        const customFieldBorderColor_2: string;
        export { customFieldBorderColor_2 as customFieldBorderColor };
        const customActiveFieldBorderColor_2: string;
        export { customActiveFieldBorderColor_2 as customActiveFieldBorderColor };
        const customColor_2: string;
        export { customColor_2 as customColor };
        const customActiveColor_2: string;
        export { customActiveColor_2 as customActiveColor };
        const customDiscardedColor_2: string;
        export { customDiscardedColor_2 as customDiscardedColor };
        const customFieldColor_2: string;
        export { customFieldColor_2 as customFieldColor };
        const customActiveFieldColor_2: string;
        export { customActiveFieldColor_2 as customActiveFieldColor };
        const customFrameColor_2: string;
        export { customFrameColor_2 as customFrameColor };
        const customHoverColor_2: string;
        export { customHoverColor_2 as customHoverColor };
        const customSelectionColor_2: string;
        export { customSelectionColor_2 as customSelectionColor };
        const customHoverSelectionColor_2: string;
        export { customHoverSelectionColor_2 as customHoverSelectionColor };
        const customTabGroup1HeadingText_2: string;
        export { customTabGroup1HeadingText_2 as customTabGroup1HeadingText };
        const customTabGroup2HeadingText_2: string;
        export { customTabGroup2HeadingText_2 as customTabGroup2HeadingText };
        const customTabGroup3HeadingText_2: string;
        export { customTabGroup3HeadingText_2 as customTabGroup3HeadingText };
        const customTabGroup4HeadingText_2: string;
        export { customTabGroup4HeadingText_2 as customTabGroup4HeadingText };
        const customPinnedTabGroupHeadingText_2: string;
        export { customPinnedTabGroupHeadingText_2 as customPinnedTabGroupHeadingText };
        const customFocusOutlineColor_2: string;
        export { customFocusOutlineColor_2 as customFocusOutlineColor };
    }
    namespace lightTheme {
        const customBackgroundColor_3: string;
        export { customBackgroundColor_3 as customBackgroundColor };
        const customActiveBackgroundColor_3: string;
        export { customActiveBackgroundColor_3 as customActiveBackgroundColor };
        const customDiscardedBackgroundColor_3: string;
        export { customDiscardedBackgroundColor_3 as customDiscardedBackgroundColor };
        const customFieldBackgroundColor_3: string;
        export { customFieldBackgroundColor_3 as customFieldBackgroundColor };
        const customFieldBackgroundActiveColor_3: string;
        export { customFieldBackgroundActiveColor_3 as customFieldBackgroundActiveColor };
        const customFrameBackgroundColor_3: string;
        export { customFrameBackgroundColor_3 as customFrameBackgroundColor };
        const customHoverBackgroundColor_3: string;
        export { customHoverBackgroundColor_3 as customHoverBackgroundColor };
        const customHoverBackgroundShadow_3: string;
        export { customHoverBackgroundShadow_3 as customHoverBackgroundShadow };
        const customSelectionBackgroundColor_3: string;
        export { customSelectionBackgroundColor_3 as customSelectionBackgroundColor };
        const customHoverSelectionBackgroundColor_3: string;
        export { customHoverSelectionBackgroundColor_3 as customHoverSelectionBackgroundColor };
        const customActiveBorderColor_3: string;
        export { customActiveBorderColor_3 as customActiveBorderColor };
        const customFieldBorderColor_3: string;
        export { customFieldBorderColor_3 as customFieldBorderColor };
        const customActiveFieldBorderColor_3: string;
        export { customActiveFieldBorderColor_3 as customActiveFieldBorderColor };
        const customColor_3: string;
        export { customColor_3 as customColor };
        const customActiveColor_3: string;
        export { customActiveColor_3 as customActiveColor };
        const customDiscardedColor_3: string;
        export { customDiscardedColor_3 as customDiscardedColor };
        const customFieldColor_3: string;
        export { customFieldColor_3 as customFieldColor };
        const customActiveFieldColor_3: string;
        export { customActiveFieldColor_3 as customActiveFieldColor };
        const customFrameColor_3: string;
        export { customFrameColor_3 as customFrameColor };
        const customHoverColor_3: string;
        export { customHoverColor_3 as customHoverColor };
        const customSelectionColor_3: string;
        export { customSelectionColor_3 as customSelectionColor };
        const customHoverSelectionColor_3: string;
        export { customHoverSelectionColor_3 as customHoverSelectionColor };
        const customTabGroup1HeadingText_3: string;
        export { customTabGroup1HeadingText_3 as customTabGroup1HeadingText };
        const customTabGroup2HeadingText_3: string;
        export { customTabGroup2HeadingText_3 as customTabGroup2HeadingText };
        const customTabGroup3HeadingText_3: string;
        export { customTabGroup3HeadingText_3 as customTabGroup3HeadingText };
        const customTabGroup4HeadingText_3: string;
        export { customTabGroup4HeadingText_3 as customTabGroup4HeadingText };
        const customPinnedTabGroupHeadingText_3: string;
        export { customPinnedTabGroupHeadingText_3 as customPinnedTabGroupHeadingText };
        const customFocusOutlineColor_3: string;
        export { customFocusOutlineColor_3 as customFocusOutlineColor };
    }
}
export const currentThemeColors: Map<any, any>;
export const currentTheme: Map<any, any>;
export function getThemeId(): Promise<string | null>;
export function setCurrentThemeColors(key: string, value: Array<number> | string): Promise<void>;
export function getCurrentThemeBaseValues(opt?: object): Promise<object>;
export function getBaseValues(opt?: object): Promise<object>;
export function setCurrentThemeValue(opt?: object): Promise<void>;
export function sendCurrentTheme(themeId?: string): Promise<Promise<any> | null>;
export function updateCustomThemeCss(sel: string, prop?: string, value?: string): Promise<void>;
export function deleteCustomThemeCss(sel?: string): Promise<void>;
export function initCustomTheme(opt?: object): Promise<Promise<any> | null>;
export function getThemeInfo(opt?: object): Promise<any[]>;
export function setTheme(info?: any[], opt?: object): Promise<void>;
export const timeStamp: Map<any, any>;
export function applyLocalTheme(opt?: object): Promise<Promise<any> | null>;
export function applyCustomTheme(data?: object): Promise<any[]>;
export function applyTheme(opt?: object): Promise<any>;
export function setUserCss(css: string): Promise<void>;
export function getTabHeight(): Promise<boolean>;
export function setTabHeight(compact?: boolean): Promise<void>;
export function getScrollbarWidth(): Promise<boolean>;
export function setScrollbarWidth(narrow?: boolean): Promise<void>;
export function getTabGroupColorBarWidth(): Promise<boolean>;
export function setTabGroupColorBarWidth(narrow?: boolean): Promise<void>;
export function getNewTabSeparator(): Promise<boolean>;
export function setNewTabSeparator(show?: boolean): Promise<void>;
export function setActiveTabFontWeight(value: string): Promise<Promise<any> | null>;
export function applyCss(): Promise<void>;
export function setSidebarTheme(opt?: object): Promise<void>;
import { CSS_VAR_BG } from "./constant.js";
import { CSS_VAR_BG_ACTIVE } from "./constant.js";
import { CSS_VAR_BG_DISCARDED } from "./constant.js";
import { CSS_VAR_BG_FIELD } from "./constant.js";
import { CSS_VAR_BG_FIELD_ACTIVE } from "./constant.js";
import { CSS_VAR_BG_HOVER } from "./constant.js";
import { CSS_VAR_BG_HOVER_SHADOW } from "./constant.js";
import { CSS_VAR_BG_SELECT } from "./constant.js";
import { CSS_VAR_BG_SELECT_HOVER } from "./constant.js";
import { CSS_VAR_BORDER_ACTIVE } from "./constant.js";
import { CSS_VAR_BORDER_FIELD } from "./constant.js";
import { CSS_VAR_BORDER_FIELD_ACTIVE } from "./constant.js";
import { CSS_VAR_COLOR } from "./constant.js";
import { CSS_VAR_COLOR_ACTIVE } from "./constant.js";
import { CSS_VAR_COLOR_DISCARDED } from "./constant.js";
import { CSS_VAR_COLOR_FIELD } from "./constant.js";
import { CSS_VAR_COLOR_FIELD_ACTIVE } from "./constant.js";
import { CSS_VAR_COLOR_HOVER } from "./constant.js";
import { CSS_VAR_COLOR_SELECT } from "./constant.js";
import { CSS_VAR_COLOR_SELECT_HOVER } from "./constant.js";
import { CSS_VAR_HEADING_TEXT_GROUP_1 } from "./constant.js";
import { CSS_VAR_HEADING_TEXT_GROUP_2 } from "./constant.js";
import { CSS_VAR_HEADING_TEXT_GROUP_3 } from "./constant.js";
import { CSS_VAR_HEADING_TEXT_GROUP_4 } from "./constant.js";
import { CSS_VAR_HEADING_TEXT_PINNED } from "./constant.js";
import { CSS_VAR_OUTLINE_FOCUS } from "./constant.js";
