export function getTemplate(id: string): object;
export function getSidebarTabContainer(node?: object): object;
export function restoreTabContainer(container?: object): void;
export function createSidebarTab(node?: object, target?: object): object;
export function getSidebarTab(node?: object): object;
export function getSidebarTabId(node?: object): number | null;
export function getSidebarTabIds(nodes: any[]): any[];
export function getSidebarTabIndex(node: object): number | null;
export function getTabsInRange(tabA: object, tabB: object): any[];
export function getNextTab(elm: object, skipCollapsed?: boolean): object;
export function getPreviousTab(elm: object, skipCollapsed?: boolean): object;
export function isNewTab(node?: object): boolean;
export function activateTab(elm: object): Promise<any> | null;
export function scrollTabIntoView(elm?: object): Promise<void>;
export function switchTab(opt?: object): Promise<any> | null;
export function createUrlMatchString(url: string): string;
export function storeCloseTabsByDoubleClickValue(bool?: boolean): Promise<void>;
